### ISSUE TITLE
Add JWT

### ISSUE THREAD

**Issue by johnnywell** [LucasEduardoGiovanini/Desafio-Snowman#8]
The goal is to provide a token for our users, so they don't need to pass their password on every request.

We'll use the request header in the following format to pass the token:

`Authorization: Bearer <token>`

So the request body is reserved for application business only.

For this objective we'll use PyJWT to encode and decode those tokens.

## What to change

* Add a jwt_encode function to create new tokens base on user's password.
* Add a jwt_decode function to decode users tokens.
* Add a endpoint to login the user and return his token.
* Prepare the views to retrieve the token from `Authorization` header
* Add a function to check the user token.

## References
[Introduction to JSON Web Tokens](https://jwt.io/introduction/)
[PyJWT](https://github.com/jpadilla/pyjwt)
[Flask request.authorization](https://flask.palletsprojects.com/en/1.1.x/api/?highlight=request.authorization#flask.Request.authorization)

**Comment by LucasEduardoGiovanini** [comment]
Prepare the views to retrieve the token from Authorization header

**Comment by LucasEduardoGiovanini** [comment]
this topic is about insert a token dependency in functions that need login?

**Comment by LucasEduardoGiovanini** [comment]
for example:

@app.route("/users/touristSpotName", methods=['GET'])  
@token_required
def pontos_turisticos_por_nome():
    data = request.json  # solicita o json enviado pelo postman
    return pontos_turisticos_por_nome_logica(data)

where @token_required is a decorator that requires the insertion of a valid token

**Comment by johnnywell** [comment]
The `decorator` approach is a next step. First you need tho understand how to get data from the request header, so you can use it to get the `Authorization` and check the token.

So, I would create a function that receives the `request` as argument. get the token from the `Authorization` header check it, decode it, them return the user data stored on it, like the user email.

You can use this function in your views whiteout much modification on them, just calling this function.

When this is working properly I would mind how to create a decorator from that.
